### ISSUE TITLE
Beta readiness tracker

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-rust#74]
This is a tracking issue for the requirements outlined in the beta release document: https://docs.google.com/document/d/1eviggoIguOS89dgKL-8ntUOCfPP6FLWAoQkGoBDsld0/edit#

## Traces
- [ ] Stable API of every spec'd feature
- [x] SDK Implementation of every spec'd feature
- [x] Basic tracing
- [x] Named tracers
- [x] Tracers use OTEP 66 Context mechanism - This is an implementation detail and does not affect the API
## Metrics
- [ ] Documentation
- [x] Examples
- [ ] Stable API of every spec'd feature
- [ ] SDK Implementation of every spec'd feature
- [x] Basic SDK
- [ ] Add observer open-telemetry/opentelemetry-specification#430
- [ ] Remove gauge open-telemetry/opentelemetry-specification#430
- [ ] Push controller
- [ ] Pull controller
## Resources
- [x] Stable API of every spec'd feature #789
- [x] SDK Implementation of every spec'd feature
## Context Propagation
- [ ] Stable API of every spec'd feature #741
- [x] Basic context mechanism #769
- [x] Global Propagators API #777 #797
- [x] Global Context API (get and set active context) #792
- [x] SDK Implementation of every spec'd feature
- [x] Basic context mechanism #769
- [x] Global Propagators #777
## Exporters
- [ ] OpenTelemetry Native - Collector Exporter
- [ ] gRPC support
- [x] Prometheus
- [x] Jaeger
- [x] Zipkin
## Integrations
- [ ] HTTP
- [ ] gRPC
- [ ] SQL
## Examples
- [x] Manual tracing hello world example
- [x] HTTP client/server using an instrumented framework
- [x] gRPC client/server

**Comment by jtescher** [comment]
Closing this as we're moving towards GA spec 👍
